# UDS Bundle Runtime & Deployment Configuration
options:
  log_level: info

shared:
  DOMAIN: datalake.local
  STORAGE_CLASS: local-path

variables:
  il5-data-lakehouse:
    DOMAIN: datalake.local
    STORAGE_CLASS: local-path
    NAMESPACE: datalakehouse
    STORAGE_RETENTION: "true"
    SECURITY_PROFILE: il5-strict
