{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    zarf.dev/connect-name: minio
  annotations:
    zarf.dev/connect-description: "MinIO S3 Object Storage Console"
    zarf.dev/connect-url: "/"
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: minio
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    zarf.dev/connect-name: postgresql
  annotations:
    zarf.dev/connect-description: "PostgreSQL Gold Data Warehouse"
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql
{{- end }}
